#!/bin/sh
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=ibus

if command -v fcitx5 >/dev/null 2>&1; then
    fcitx5 -d &
fi
if command -v tint2 >/dev/null 2>&1; then
    pgrep -u abc tint2 >/dev/null 2>&1 || tint2 &
fi
